import csv
import random
import os

random.seed(42)

ngo_names = [
    "GreenRoots India", "Udaan Charitable Trust", "Samarth Livelihoods", "Jeevan Jyoti Sangh",
    "Pragati Mahila Sangh", "Green Future Trust", "Helping Hands Foundation", "Vikas Foundation",
    "Narmada Seva Trust", "Sahayog Trust", "Navodaya Foundation", "Arthik Vikas Kendra",
    "Prakriti Rakshak", "Dhanvantari Trust", "Ujjwal Bhavishya", "Saksham India",
    "Gram Vikas Parishad", "Sadbhavna Trust", "Anand Social Welfare", "Parivartan Foundation",
    "Asha Kiran Society", "Vidya Bharti Trust", "Roshni Foundation", "Sahaya",
    "Greenleaf India", "Jan Kalyan Samiti", "Umeed", "Vasundhara", "Sahajdoor", "Jeevika",
    "Aarohi Foundation", "Prayas Trust", "Nirman Seva", "Samarthan Foundation",
    "Vidushi Foundation", "Arogya Seva", "Prakriti Seva Trust", "Jyoti Foundation",
    "Pragya Seva Trust", "Sahara Foundation", "Narmada Seva Sangh", "Uday Foundation",
    "Shiksha Seva Trust", "Vikas Seva Foundation", "Saksham Seva Trust", "Anand Seva Trust",
    "Parivartan Seva Foundation", "Asha Seva Trust", "Vidya Seva Trust", "Roshni Seva Trust",
    "Sahaya Seva Trust", "Greenleaf Seva Trust", "Jan Kalyan Seva Trust", "Umeed Seva Trust",
    "Vasundhara Seva Trust", "Sahajdoor Seva Trust", "Jeevika Seva Trust", "Aarohi Seva Trust",
    "Prayas Seva Trust", "Nirman Seva Trust", "Samarthan Seva Trust", "Vidushi Seva Trust",
    "Arogya Seva Trust", "Prakriti Seva Trust", "Jyoti Seva Trust", "Pragya Seva Trust",
    "Sahara Seva Trust", "Uday Seva Trust", "Shiksha Seva Foundation", "Vikas Seva Sangh",
    "Saksham Seva Sangh", "Anand Seva Sangh", "Parivartan Seva Sangh", "Asha Seva Sangh",
    "Vidya Seva Sangh", "Roshni Seva Sangh", "Sahaya Seva Sangh", "Greenleaf Seva Sangh",
    "Jan Kalyan Seva Sangh", "Umeed Seva Sangh", "Vasundhara Seva Sangh", "Sahajdoor Seva Sangh",
    "Jeevika Seva Sangh", "Aarohi Seva Sangh", "Prayas Seva Sangh", "Nirman Seva Sangh",
    "Samarthan Seva Sangh", "Vidushi Seva Sangh", "Arogya Seva Sangh", "Prakriti Seva Sangh",
    "Jyoti Seva Sangh", "Pragya Seva Sangh", "Sahara Seva Sangh", "Uday Seva Sangh",
    "Shiksha Seva Sangh", "Vikas Seva Kendra", "Saksham Seva Kendra", "Anand Seva Kendra",
    "Parivartan Seva Kendra", "Asha Seva Kendra", "Vidya Seva Kendra", "Roshni Seva Kendra",
    "Sahaya Seva Kendra", "Greenleaf Seva Kendra", "Jan Kalyan Seva Kendra", "Umeed Seva Kendra",
    "Vasundhara Seva Kendra", "Sahajdoor Seva Kendra", "Jeevika Seva Kendra", "Aarohi Seva Kendra",
    "Prayas Seva Kendra", "Nirman Seva Kendra", "Samarthan Seva Kendra", "Vidushi Seva Kendra",
    "Arogya Seva Kendra", "Prakriti Seva Kendra", "Jyoti Seva Kendra", "Pragya Seva Kendra",
    "Sahara Seva Kendra", "Uday Seva Kendra", "Shiksha Seva Kendra", "Vikas Seva Foundation",
    "Saksham Seva Foundation", "Anand Seva Foundation", "Parivartan Seva Foundation",
    "Asha Seva Foundation", "Vidya Seva Foundation", "Roshni Seva Foundation", "Sahaya Seva Foundation",
    "Greenleaf Seva Foundation", "Jan Kalyan Seva Foundation", "Umeed Seva Foundation",
    "Vasundhara Seva Foundation", "Sahajdoor Seva Foundation", "Jeevika Seva Foundation",
    "Aarohi Seva Foundation", "Prayas Seva Foundation", "Nirman Seva Foundation",
    "Samarthan Seva Foundation", "Vidushi Seva Foundation", "Arogya Seva Foundation",
    "Prakriti Seva Foundation", "Jyoti Seva Foundation", "Pragya Seva Foundation",
    "Sahara Seva Foundation", "Uday Seva Foundation", "Shiksha Seva Foundation",
    "Vikas Aarogya Seva", "Saksham Aarogya Seva", "Anand Aarogya Seva",
    "Parivartan Aarogya Seva", "Asha Aarogya Seva", "Vidya Aarogya Seva",
    "Roshni Aarogya Seva", "Sahaya Aarogya Seva", "Greenleaf Aarogya Seva",
    "Jan Kalyan Aarogya Seva", "Umeed Aarogya Seva", "Vasundhara Aarogya Seva",
    "Sahajdoor Aarogya Seva", "Jeevika Aarogya Seva", "Aarohi Aarogya Seva",
    "Prayas Aarogya Seva", "Nirman Aarogya Seva", "Samarthan Aarogya Seva",
    "Vidushi Aarogya Seva", "Arogya Aarogya Seva", "Prakriti Aarogya Seva",
    "Jyoti Aarogya Seva", "Pragya Aarogya Seva", "Sahara Aarogya Seva",
    "Uday Aarogya Seva", "Shiksha Aarogya Seva", "Vikas Van Seva",
    "Saksham Van Seva", "Anand Van Seva", "Parivartan Van Seva",
    "Asha Van Seva", "Vidya Van Seva", "Roshni Van Seva", "Sahaya Van Seva",
    "Greenleaf Van Seva", "Jan Kalyan Van Seva", "Umeed Van Seva",
    "Vasundhara Van Seva", "Sahajdoor Van Seva", "Jeevika Van Seva",
    "Aarohi Van Seva", "Prayas Van Seva", "Nirman Van Seva", "Samarthan Van Seva",
    "Vidushi Van Seva", "Arogya Van Seva", "Prakriti Van Seva", "Jyoti Van Seva",
    "Pragya Van Seva", "Sahara Van Seva", "Uday Van Seva", "Shiksha Van Seva",
    "Vikas Seva Initiative", "Saksham Seva Initiative", "Anand Seva Initiative",
    "Parivartan Seva Initiative", "Asha Seva Initiative", "Vidya Seva Initiative",
    "Roshni Seva Initiative", "Sahaya Seva Initiative", "Greenleaf Seva Initiative",
    "Jan Kalyan Seva Initiative", "Umeed Seva Initiative", "Vasundhara Seva Initiative",
    "Sahajdoor Seva Initiative", "Jeevika Seva Initiative", "Aarohi Seva Initiative",
    "Prayas Seva Initiative", "Nirman Seva Initiative", "Samarthan Seva Initiative",
    "Vidushi Seva Initiative", "Arogya Seva Initiative", "Prakriti Seva Initiative",
    "Jyoti Seva Initiative", "Pragya Seva Initiative", "Sahara Seva Initiative",
    "Uday Seva Initiative", "Shiksha Seva Initiative", "Vikas Education Seva",
    "Saksham Education Seva", "Anand Education Seva", "Parivartan Education Seva",
    "Asha Education Seva", "Vidya Education Seva", "Roshni Education Seva",
    "Sahaya Education Seva", "Greenleaf Education Seva", "Jan Kalyan Education Seva",
    "Umeed Education Seva", "Vasundhara Education Seva", "Sahajdoor Education Seva",
    "Jeevika Education Seva", "Aarohi Education Seva", "Prayas Education Seva",
    "Nirman Education Seva", "Samarthan Education Seva", "Vidushi Education Seva",
    "Arogya Education Seva", "Prakriti Education Seva", "Jyoti Education Seva",
    "Pragya Education Seva", "Sahara Education Seva", "Uday Education Seva",
    "Shiksha Education Seva", "Vikas Health Seva", "Saksham Health Seva",
    "Anand Health Seva", "Parivartan Health Seva", "Asha Health Seva",
    "Vidya Health Seva", "Roshni Health Seva", "Sahaya Health Seva",
    "Greenleaf Health Seva", "Jan Kalyan Health Seva", "Umeed Health Seva",
    "Vasundhara Health Seva", "Sahajdoor Health Seva", "Jeevika Health Seva",
]

titles = [
    "Girls' STEM Scholarships", "Digital Literacy for Rural Schools", "Vocational Training Hub",
    "Anaemia-Free District", "Women SHG Network", "Clean Water Initiative",
    "Digital Literacy Program", "Maternal Health Camps", "River Cleaning Drive",
    "Polyclinic for Tribal Areas", "Scholarship for First-Gen Students", "Livelihood Training",
    "Community Forestry", "Mobile Health Van", "After-School Tutoring",
    "Skill Development Centre", "Rural Water Purification", "Women Safety Helpline",
    "Senior Citizen Care", "Solar Electrification of Schools", "Mobile Health Units",
    "STEM Labs in Government Schools", "Girls' Education Support", "Disability Rehabilitation Centre",
    "Mangrove Restoration", "Primary Healthcare Camp", "Self-Employment for Women",
    "Plastic Waste Management", "Financial Literacy Program", "Community Health Workers Training",
    "Nutrition Awareness Drive", "Eye Care Camp", "Mid-Day Meal Enhancement",
    "Rainwater Harvesting", "Rural Library Network", "Craft Revival Programme",
    "Anti-Drug Campaign", "Legal Aid Clinic", "Menstrual Hygiene Initiative",
    "Skill India Partnership", "Village Electrification", "Clean Ganga Awareness",
    "Organic Farming Training", "Street Children Rehabilitation", "Tuberculosis Detection Camp",
    "Digital Payment Literacy", "Rural Telecom Access", "Children's Nutrition Programme",
    "Senior Pension Support", "Accessible Infrastructure Audit", "Mental Health Awareness",
    "Sanitation Block Construction", "Women in Tech Training", "Artisan Market Access",
    "Farm Mechanization Support", "Solar Pump Installation", "Biodiversity Survey",
    "Transitional Housing Programme", "Teacher Training Institute", "Youth Sports Development",
    "Waste Segregation Drive", "Cataract Surgery Camp", "Telemedicine Network",
    "Rural Banking Access", "Elderly Care Helpline", "Skill Upgrade for Workers",
    "Cooperative Formation", "Water Quality Testing", "Seed Bank Initiative",
    "Toddler Development Centre", "Heritage Conservation", "Community Radio Station",
    "Micro-Enterprise Incubation", "Thalassemia Support", "School Meal Quality Improvement",
    "Accessible Voting Initiative", "Fire Safety Awareness", "Mid-Career Reskilling",
    "Drought Relief Programme", "School Infrastructure Upgrade", "Nutrition Garden",
    "Disaster Preparedness Training", "Rural Broadband Access", "Blood Donation Network",
    "Differently-Abled Employment", "Weaving Revival Programme", "Solar Street Lights",
    "Adolescent Girls Programme", "Organ Donor Awareness", "Watershed Management",
    "Child Labour Rehabilitation", "Health Insurance Literacy", "Vocational Guidance Centre",
    "Eco-Tourism Development", "Anemia Prevention Drive", "Rural Insurance Awareness",
    "Women's Legal Literacy", "Playground Construction", "Waste Recycling Initiative",
    "Rural Diagnostic Centre", "Cultural Exchange Programme", "Farmer Producer Organisation",
    "Drug De-Addiction Centre", "Elderly Nutrition Programme", "Infrastructure Monitoring",
    "Community Health Insurance", "Digital India Programme", "Women Cooperative Banks",
    "Clean Energy Awareness", "Rural Health Data System", "School Counselling Programme",
    "Handloom Revival Programme", "Water ATMs Installation", "Vocational Guidance for Youth",
    "Anti-Tobacco Campaign", "Urban Slum Rehabilitation", "Night School Programme",
    "Solar Cooker Distribution", "Mobile Veterinary Unit", "Legal Awareness Camp",
    "Geriatric Care Programme", "Youth Leadership Programme", "Rural Cold Storage",
    "Textile Skill Training", "Amphibian Conservation", "Agricultural Extension Services",
    "Senior Citizen Digital Literacy", "Hospital Equipment Donation", "School Lab Setup",
    "Rural Sanitary Napkin Unit", "Wildlife Corridor Protection", "Village Knowledge Centre",
    "Medical Camp Van", "Anti-Poverty Initiative", "Youth Employment Programme",
    "Rural Housing Programme", "Scholarship for Disabled", "Community Medicine Garden",
    "Solar Power Training", "Water Conservation Awareness", "Elderly Home Delivery",
    "Health Camp in Slums", "Digital Classrooms", "Cultural Preservation Programme",
    "Spinal Injury Rehabilitation", "Rural Market Development", "Toy Library Initiative",
    "Mobile Blood Bank", "Agricultural Innovation Hub", "Special Education Programme",
    "Veterinary Aid Camp", "Community Health Survey", "Urban Farming Initiative",
    "Braille Literacy Programme", "Orphanage Support Programme", "Solar Water Heater Distribution",
    "Dental Health Camp", "Forest Guard Training", "Women Entrepreneurship Programme",
    "Nutrition for Pregnant Women", "Rural Internet Access", "Children's Science Fair",
    "Disaster Relief Warehouse", "Community Library Network", "Traditional Medicine Centre",
    "Rural CCTV Safety Network", "Youth Exchange Programme", "Football Academy for Slum Kids",
    "Organic Certification Support", "Women's Self-Help Credit", "Rural Ambulance Service",
    "Senior Citizen Day Care", "Health Card Distribution", "Rain Water Recharge Pits",
    "Maternity Home Upgrade", "Street Light Installation", "Village Handpump Repair",
    "Balwadi Support Programme", "Tree Plantation Drive", "Digital Health Records",
    "Women Police Support", "Rural MBA Programme", "Autism Support Centre",
    "Clean Cooking Fuel Programme", "Nursing Training College", "Tribal Art Promotion",
    "Mobile Library Van", "Eye Screening Programme", "Rural Entrepreneurship Cell",
    "Paralysis Rehabilitation", "Children's Parliament", "Wetland Conservation",
    "Rural E-Governance Centre", "Homeopathy Clinic", "Youth Skills Assessment",
    "Textile Waste Recycling", "Community Health Fund", "Slum Sanitation Programme",
    "Solar LED Lamp Distribution", "Rural Primary Care Centre", "Adolescent Health Programme",
    "Rural School Playground", "Ayurveda Health Camp", "Cultural Village Programme",
    "Mid-Day Meal Kitchen", "Water Pipeline Installation", "Old Age Allowance Programme",
]

sectors = ["education", "health", "environment", "water and sanitation", "women empowerment",
           "livelihood", "technology", "community development"]

regions = ["Maharashtra", "Tamil Nadu", "Rajasthan", "Bihar", "Gujarat", "Karnataka",
           "Uttar Pradesh", "Madhya Pradesh", "Kerala", "Delhi NCR", "Odisha", "Northeast",
           "Andhra Pradesh", "West Bengal", "Punjab", "Haryana", "Jharkhand", "Chhattisgarh",
           "Uttarakhand", "Himachal Pradesh", "Assam", "Goa", "Jammu and Kashmir"]

# Output path
out = os.path.join(os.getcwd(), "backend", "data", "sample_proposals.csv")

rows = []
for i in range(250):
    ngo = ngo_names[i % len(ngo_names)]
    title = titles[i % len(titles)]
    sector = sectors[i % len(sectors)]
    region = regions[i % len(regions)]
    amount = random.randint(50000, 2500000)
    beneficiaries = random.randint(50, 8000)
    rows.append([ngo, title, sector, region, str(amount), str(beneficiaries)])

with open(out, "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(["ngo_name", "title", "sector", "region", "requested_amount", "beneficiaries"])
    writer.writerows(rows)

print(f"Generated {len(rows)} rows -> {out}")
