import { useState, useRef } from 'react'
import { jsPDF } from 'jspdf'
import * as XLSX from 'xlsx'

function formatCurrency(amount) {
  const num = parseFloat(amount)
  if (isNaN(num)) return amount || '—'
  if (num >= 10000000) return `₹${(num / 10000000).toFixed(2)} Cr`
  if (num >= 100000) return `₹${(num / 100000).toFixed(2)} L`
  return `₹${num.toLocaleString('en-IN')}`
}

const CSR2_SECTIONS = {
  company: {
    title: 'Company Details',
    fields: [
      { key: 'cin', label: 'CIN', auto: 'U74999MH2020PTC123456' },
      { key: 'company_name', label: 'Company Name', auto: 'Acme Corp Pvt. Ltd.' },
      { key: 'email', label: 'Official Email', auto: 'csr@acmecorp.com' },
      { key: 'sector', label: 'Business Sector', auto: 'Information Technology' },
    ],
  },
  financials: {
    title: 'Financial Details (FY 2024-25)',
    fields: [
      { key: 'net_worth', label: 'Net Worth', auto: '500000000', isMoney: true },
      { key: 'turnover', label: 'Turnover', auto: '2000000000', isMoney: true },
      { key: 'net_profit', label: 'Net Profit', auto: '150000000', isMoney: true },
      { key: 'csr_obligation', label: 'CSR Obligation (2%)', auto: '10000000', isMoney: true },
      { key: 'csr_spent', label: 'Total CSR Spent', auto: '8400000', isMoney: true },
    ],
  },
  projects: {
    title: 'Project Details',
    fields: [
      { key: 'total_projects', label: 'Total Projects', auto: '5' },
      { key: 'ongoing', label: 'Ongoing Projects', auto: '3' },
      { key: 'schedule_vii', label: 'Schedule VII Areas', auto: 'Education, Healthcare, Environment' },
      { key: 'beneficiaries', label: 'Total Beneficiaries', auto: '12500' },
    ],
  },
  compliance: {
    title: 'Compliance & Filing',
    fields: [
      { key: 'committee', label: 'CSR Committee Formed', auto: 'Yes' },
      { key: 'policy', label: 'CSR Policy Approved', auto: 'Yes' },
      { key: 'impact', label: 'Impact Assessment Done', auto: 'Yes' },
      { key: 'unspent', label: 'Unspent CSR Account Opened', auto: 'Yes' },
    ],
  },
}

export default function CSR2Form() {
  const [formData, setFormData] = useState(() => {
    const filled = {}
    Object.values(CSR2_SECTIONS).forEach(sec => sec.fields.forEach(f => { filled[f.key] = f.auto || '' }))
    return filled
  })
  const [activeSection, setActiveSection] = useState('company')
  const [exporting, setExporting] = useState(null)

  const totalFields = Object.values(CSR2_SECTIONS).reduce((s, sec) => s + sec.fields.length, 0)
  const filledFields = Object.values(formData).filter(v => v && v !== '').length
  const completionPct = totalFields > 0 ? (filledFields / totalFields) * 100 : 0

  const deadline = new Date('2025-09-30')
  const daysLeft = Math.ceil((deadline - new Date()) / (1000 * 60 * 60 * 24))
  const currentSection = CSR2_SECTIONS[activeSection]

  // ── PDF Export ──
  const exportPDF = () => {
    setExporting('pdf')
    try {
      const doc = new jsPDF('p', 'mm', 'a4')
      const pageW = 210, margin = 20, contentW = pageW - 2 * margin
      let y = 20

      // Title
      doc.setFontSize(18)
      doc.setFont('helvetica', 'bold')
      doc.text('CSR-2 Annual Return', margin, y)
      y += 8

      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(100, 100, 100)
      doc.text(`Filed under Section 135 of the Companies Act, 2013`, margin, y)
      y += 5
      doc.text(`Generated: ${new Date().toLocaleDateString('en-IN')} | Deadline: 30 September 2025`, margin, y)
      y += 10

      // Divider
      doc.setDrawColor(200, 200, 200)
      doc.line(margin, y, pageW - margin, y)
      y += 8

      // Sections
      Object.entries(CSR2_SECTIONS).forEach(([key, sec]) => {
        // Section header
        doc.setFontSize(11)
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(31, 75, 67)
        doc.text(sec.title, margin, y)
        y += 7

        sec.fields.forEach(field => {
          if (y > 270) { doc.addPage(); y = 20 }

          const value = formData[field.key] || '—'
          const displayValue = field.isMoney ? formatCurrency(value) : value

          doc.setFontSize(9)
          doc.setFont('helvetica', 'normal')
          doc.setTextColor(138, 133, 120)
          doc.text(field.label, margin, y)

          doc.setFont('helvetica', 'bold')
          doc.setTextColor(27, 33, 31)
          doc.text(String(displayValue), margin + 60, y)

          y += 6
        })

        y += 3
        doc.setDrawColor(220, 220, 220)
        doc.line(margin, y, pageW - margin, y)
        y += 6
      })

      // Footer
      if (y > 260) { doc.addPage(); y = 20 }
      y += 5
      doc.setFontSize(8)
      doc.setFont('helvetica', 'italic')
      doc.setTextColor(150, 150, 150)
      doc.text('This document was generated by CSR Helper — Intelligent Fund Allocation Platform', margin, y)

      doc.save('CSR-2-Annual-Return.pdf')
    } finally {
      setTimeout(() => setExporting(null), 500)
    }
  }

  // ── Excel Export ──
  const exportExcel = () => {
    setExporting('excel')
    try {
      const rows = []
      Object.entries(CSR2_SECTIONS).forEach(([key, sec]) => {
        rows.push({ Section: sec.title, Field: '', Value: '' })
        sec.fields.forEach(field => {
          const value = formData[field.key] || ''
          rows.push({
            Section: '',
            Field: field.label,
            Value: field.isMoney ? formatCurrency(value) : value,
          })
        })
        rows.push({ Section: '', Field: '', Value: '' })
      })

      const ws = XLSX.utils.json_to_sheet(rows)
      // Column widths
      ws['!cols'] = [{ wch: 30 }, { wch: 30 }, { wch: 25 }]

      const wb = XLSX.utils.book_new()
      XLSX.utils.book_append_sheet(wb, ws, 'CSR-2 Filing')
      XLSX.writeFile(wb, 'CSR-2-Annual-Return.xlsx')
    } finally {
      setTimeout(() => setExporting(null), 500)
    }
  }

  return (
    <div className="space-y-5 animate-fade-in">
      <h1 className="font-serif text-xl" style={{ color: 'var(--ink)' }}>CSR-2 Filing</h1>

      {/* Deadline + completion */}
      <div className="flex gap-px" style={{ background: 'var(--rule)' }}>
        {[
          { label: 'Deadline', value: daysLeft > 0 ? `${daysLeft} days` : 'Overdue' },
          { label: 'Completion', value: `${completionPct.toFixed(0)}%` },
          { label: 'Fields', value: `${filledFields}/${totalFields}` },
        ].map((stat, i) => (
          <div key={i} className="flex-1 p-4" style={{ background: 'var(--paper)' }}>
            <p className="stat-label">{stat.label}</p>
            <p className="stat-value transition-all duration-300">{stat.value}</p>
          </div>
        ))}
      </div>

      {/* Progress */}
      <div className="h-1 rounded-sm overflow-hidden" style={{ background: 'var(--rule)' }}>
        <div className="h-full rounded-sm transition-all duration-700 ease-out" style={{ width: `${completionPct}%`, background: 'var(--petrol)' }} />
      </div>

      {/* Section tabs */}
      <div className="flex gap-px overflow-x-auto" style={{ background: 'var(--rule)' }}>
        {Object.entries(CSR2_SECTIONS).map(([key, sec]) => (
          <button key={key} onClick={() => setActiveSection(key)}
            className="px-4 py-2 text-xs font-medium whitespace-nowrap transition-all duration-200"
            style={{
              background: activeSection === key ? 'var(--paper)' : 'var(--parchment)',
              color: activeSection === key ? 'var(--petrol)' : 'var(--stone)',
              borderBottom: activeSection === key ? '2px solid var(--petrol)' : '2px solid transparent',
            }}>
            {sec.title.split(' ')[0]}
          </button>
        ))}
      </div>

      {/* Form fields */}
      <div className="p-5 transition-all duration-300" style={{ background: 'var(--paper)', border: '1px solid var(--rule)' }}>
        <p className="section-label mb-4">{currentSection.title}</p>
        <div className="space-y-4">
          {currentSection.fields.map((field, i) => (
            <div key={field.key} className="animate-fade-in" style={{ animationDelay: `${i * 50}ms` }}>
              <label className="section-label block mb-1">{field.label}</label>
              <input type="text" value={formData[field.key] || ''}
                onChange={e => setFormData(prev => ({ ...prev, [field.key]: e.target.value }))}
                className="input transition-all duration-200" />
            </div>
          ))}
        </div>
      </div>

      {/* Export buttons */}
      <div className="flex gap-2">
        <button onClick={exportPDF} disabled={exporting === 'pdf'} className="btn-primary flex items-center gap-2">
          {exporting === 'pdf' ? (
            <span className="flex items-center gap-2">
              <div className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin" />
              Generating…
            </span>
          ) : (
            <>
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={1.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m2.25 0H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
              </svg>
              Export PDF
            </>
          )}
        </button>
        <button onClick={exportExcel} disabled={exporting === 'excel'} className="btn-secondary flex items-center gap-2">
          {exporting === 'excel' ? (
            <span className="flex items-center gap-2">
              <div className="w-3 h-3 border-2 border-current/30 border-t-current rounded-full animate-spin" />
              Generating…
            </span>
          ) : (
            <>
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={1.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
              </svg>
              Export Excel
            </>
          )}
        </button>
      </div>
    </div>
  )
}
